export enum AreaAtencion {
  ATENCION_AL_CLIENTE = 'ATENCION_AL_CLIENTE',
  RETENCIONES = 'RETENCIONES',
  VENTAS = 'VENTAS',
  SOPORTE_TECNICO = 'SOPORTE_TECNICO',
  COBRANZAS = 'COBRANZAS',
  AGENDAMIENTO_DE_CITAS = 'AGENDAMIENTO_DE_CITAS'
}
