export enum RoleComplete {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_SUPERVISOR_TI = 'ROLE_SUPERVISOR_TI',
  ROLE_AGENTE_TI = 'ROLE_AGENTE_TI',
  ROLE_JEFE_OPERACION = 'ROLE_JEFE_OPERACION',
  ROLE_SUPERVISOR = 'ROLE_SUPERVISOR',
  ROLE_COLABORADOR = 'ROLE_COLABORADOR'
}
