export enum RoleRegular {
  ADMIN = 'ADMIN',
  SUPERVISOR_TI = 'SUPERVISOR_TI',
  AGENTE_TI = 'AGENTE_TI',
  JEFE_OPERACION = 'JEFE_OPERACION',
  SUPERVISOR = 'SUPERVISOR',
  COLABORADOR = 'COLABORADOR'
}
